/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity;
import com.samedov.annotation.Prove;
import com.samedov.annotation.Complexity;


/**
 * @author Andrea Boriero
 */
public class DB2IdentityColumnSupport extends IdentityColumnSupportImpl {

	public static final DB2IdentityColumnSupport INSTANCE = new DB2IdentityColumnSupport();

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public boolean supportsInsertSelectIdentity() {
		return true;
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentitySelectString(String table, String column, int type) {
		return "values identity_val_local()";
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentityColumnString(int type) {
		return "generated by default as identity";
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentityInsertString() {
		return "default";
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String appendIdentitySelectToInsert(String identityColumnName, String insertString) {
		return "select " + identityColumnName + " from final table ( " + insertString + " )"; //TODO: should it be 'from new table'?
	}
}
