/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity;

import org.hibernate.dialect.DatabaseVersion;
import com.samedov.annotation.Prove;
import com.samedov.annotation.Complexity;

/**
 * @author Andrea Boriero
 */
public class HSQLIdentityColumnSupport extends IdentityColumnSupportImpl {
	final private DatabaseVersion dbVersion;

	public HSQLIdentityColumnSupport(DatabaseVersion dbVersion) {
		this.dbVersion = dbVersion;
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentityColumnString(int type) {
		//not null is implicit
		return "generated by default as identity (start with 1)";
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentitySelectString(String table, String column, int type) {
		return "call identity()";
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentityInsertString() {
		return dbVersion.isBefore( 2 ) ? "null" : "default";
	}
}
