/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity;

import static org.hibernate.internal.util.StringHelper.unquote;
import com.samedov.annotation.Prove;
import com.samedov.annotation.Complexity;

/**
 * @author Andrea Boriero
 */
public class PostgreSQLIdentityColumnSupport extends IdentityColumnSupportImpl {

	public static final PostgreSQLIdentityColumnSupport INSTANCE = new PostgreSQLIdentityColumnSupport();
	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentitySelectString(String table, String column, int type) {
		return "select currval('" + unquote(table) + '_' + unquote(column) + "_seq')";
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentityColumnString(int type) {
		return "generated by default as identity";
	}
}
