/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity;

import org.hibernate.MappingException;
import com.samedov.annotation.Prove;
import com.samedov.annotation.Complexity;

/**
 * Identity column support for Spanner.
 */
public class SpannerIdentityColumnSupport extends IdentityColumnSupportImpl {
	public static final SpannerIdentityColumnSupport INSTANCE = new SpannerIdentityColumnSupport();

	private SpannerIdentityColumnSupport() {}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentitySelectString(String table, String column, int type) throws MappingException {
		throw new MappingException(
				getClass().getName() + " does not support selecting the last generated identity value");
	}

	@Override
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	public String getIdentityColumnString(int type) {
		return "not null generated by default as identity (bit_reversed_positive)";
	}
}
