/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.generator.values;

import org.hibernate.action.queue.spi.plan.FlushOperation;
import org.hibernate.engine.jdbc.mutation.JdbcValueBindings;
import org.hibernate.engine.jdbc.mutation.group.PreparedStatementDetails;
import org.hibernate.engine.spi.SessionFactoryImplementor;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.generator.EventType;
import org.hibernate.jdbc.Expectation;
import org.hibernate.sql.model.ast.builder.TableMutationBuilder;
import org.hibernate.sql.results.jdbc.spi.JdbcValuesMappingProducer;

import java.sql.PreparedStatement;
import com.samedov.annotation.Prove;
import com.samedov.annotation.Complexity;

/**
 * Each implementation defines a strategy for retrieving values
 * {@linkplain org.hibernate.generator.OnExecutionGenerator generated by
 * the database} after execution of a mutation statement.
 * <p>
 * An implementation controls:
 * <ul>
 * <li>building the SQL mutation statement, and
 * <li>retrieving the generated values using JDBC.
 * </ul>
 *
 * @author Marco Belladelli
 * @see org.hibernate.generator.OnExecutionGenerator
 * @since 6.5
 */
public interface GeneratedValuesMutationDelegate {
	/**
	 * Create a {@link TableMutationBuilder} instance used to build table mutations for this delegate.
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	TableMutationBuilder<?> createTableMutationBuilder(Expectation expectation, SessionFactoryImplementor sessionFactory);

	/**
	 * Create a {@link PreparedStatement} from the provided {@code sql} based on the delegate needs.
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	PreparedStatement prepareStatement(String sql, SharedSessionContractImplementor session);

	/**
	 * Perform the {@code mutation} and extract the database-generated values.
	 *
	 * @see #createTableMutationBuilder
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	GeneratedValues performMutation(
			PreparedStatementDetails statementDetails,
			JdbcValueBindings valueBindings,
			Object entity,
			SharedSessionContractImplementor session);

	/**
	 * Perform the {@code mutation} and extract the database-generated values.
	 *
	 * @see #createTableMutationBuilder
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	GeneratedValues performGraphMutation(
			FlushOperation operation,
			Object entity,
			SharedSessionContractImplementor session);

	/**
	 * Returns the timing this generated values delegate handles.
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	EventType getTiming();

	/**
	 * Returns {@code true} when this delegate supports retrieving arbitrary generated values,
	 * or {@code false} when it only supports identifiers.
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	boolean supportsArbitraryValues();

	/**
	 * Returns {@code true} when this delegate supports retrieving the {@link org.hibernate.annotations.RowId} value.
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	boolean supportsRowId();

	/**
	 * Retrieve the {@linkplain JdbcValuesMappingProducer mapping producer} used to read the generated values.
	 */
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	JdbcValuesMappingProducer getGeneratedValuesMappingProducer();
}
