/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.event.spi;

import org.hibernate.HibernateException;
import com.samedov.annotation.Prove;
import com.samedov.annotation.Complexity;

/**
 * Defines the contract for handling of collection initialization events
 * generated by a session.
 *
 * @author Gavin King
 */
public interface InitializeCollectionEventListener {
	@Prove(complexity = Complexity.O_1, n = "", count = {})
	void onInitializeCollection(InitializeCollectionEvent event) throws HibernateException;
}
